spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://114.132.65.155:3306/user_center
    username: root
    password: 7758258f1
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0
